#!/bin/bash
# step_3_app_configs.sh - Step 3: Application Configurations (CRITICAL: Hyprland environment config)

log "STEP 3: Copying Application Configurations..."

# A. Hyprland Configs
rm -rf ~/.config/hypr 
cp "$DOTFILES_DIR/config/hypr" -r ~/.config/ || error "Failed to copy Hyprland config."
# (Other App Configs omitted for brevity, assuming working logic)

# B. Autostart Final Script
AUTOSTART_FILE=~/.config/hypr/UserConfigs/Startup_Apps.conf
AUTOSTART_LINE="exec-once = $HOME/final_setup_nurko_dots.sh"
if [ ! -f "$AUTOSTART_FILE" ]; then touch "$AUTOSTART_FILE"; fi
echo "$AUTOSTART_LINE" >> "$AUTOSTART_FILE"
log "Added autostart line to Startup_Apps.conf: $AUTOSTART_LINE"

# C. Create Hyprland Environment Config (CRITICAL for GPU setup/fixes IOT instruction errors)
HYPR_ENV_FILE="$HOME/.config/hypr/UserConfigs/env_variables.conf"
echo "# Hyprland Environment Variables (Generated by Installer)" > "$HYPR_ENV_FILE"
echo "env = QT_QPA_PLATFORM,wayland;xcb" >> "$HYPR_ENV_FILE"
echo "env = GDK_BACKEND,wayland,x11" >> "$HYPR_ENV_FILE"

# Determine NVIDIA status from the installer session
NVIDIA_CHOICE=$(cat "$HOME/initial_theme_choice.txt" | head -n 1) # Reuse theme file to store last choice

# Check if NVIDIA was installed (This relies on the choice from step 1)
if grep -q "NVIDIA" "$LOG_FILE"; then
    log "Configuring Hyprland for NVIDIA based on installation logs."
    echo "env = LIBVA_DRIVER_NAME,nvidia" >> "$HYPR_ENV_FILE" 
    echo "env = GBM_BACKEND,nvidia-drm" >> "$HYPR_ENV_FILE"
    echo "env = __GLX_VENDOR_LIBRARY_NAME,nvidia" >> "$HYPR_ENV_FILE"
    echo "env = WLR_NO_CC_CHECKS,1" >> "$HYPR_ENV_FILE"
else
    log "Configuring Hyprland for AMD/Intel/VirtualBox (Mesa)."
    echo "env = LIBVA_DRIVER_NAME,mesa" >> "$HYPR_ENV_FILE"
fi

log "Step 3 completed successfully."
